### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ghost** [airspy/firmware#16]
Hi 

I'm currently experiencing an error whilst attempting to build the firmware via the official instructions:
https://github.com/airspy/firmware/wiki/Linux-how-to-build-airspy-firmware

`sudo python get-pip.py`

`Traceback (most recent call last):
  File "get-pip.py", line 17474, in <module>
    main()
  File "get-pip.py", line 17466, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 17406, in bootstrap
    import pip
  File "/tmp/tmppOvIE5/pip.zip/pip/__init__.py", line 11, in <module>
  File "/tmp/tmppOvIE5/pip.zip/pip/vcs/mercurial.py", line 9, in <module>
  File "/tmp/tmppOvIE5/pip.zip/pip/download.py", line 22, in <module>
  File "/tmp/tmppOvIE5/pip.zip/pip/_vendor/requests/__init__.py", line 53, in <module>
  File "/tmp/tmppOvIE5/pip.zip/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 70, in <module>
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'`

Environment:

```
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie
```

Is there a simple solution to resolve the above missing attribute error?

**Comment by bvernoux** [comment]
This problem comes from your system please check
http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

**Comment by bvernoux** [comment]
Issue with your system/install without any feedback I have closed this issue
